### ISSUE TITLE
Rare crash on loading into worlds

### ISSUE THREAD

**Issue by DeeDoubleYous** [MysteriousAges/SimpleDim#6]
I am using this "plains { id: 45; type: singleBiome; Biome: plains }" in a config called Dimentions.cfg in xcompcraft. But the MultiMC console tells me "[19:06:32] [Client thread/ERROR] [XCompCraft]: Configuration for plains is invalid, and will be ignored!" and when I try and tpx to dimension 45 in the chat "Could not get world for dimension 45. No tp" comes up.
This dimension "trateotu{ id: 42; type: void; spawn: (0,64,0)}" and this dimension works "flat { id: 46; type: superflat; generator: "2;7,2x3,2;1;village" }".

**Comment by lefty82** [comment]
It seems that the single biome gen is indeed broken. I used the following code in the config:

```
dimMiningworlddim { id: 16; type: singleBiome; biome: Desert; }
item porterMiningworlddim { forDim: dimMiningworlddim; type: accesscard; colours: [0xffffcc]; displayName: "Mining World Dimension Pass"; }
```

And according to the log everything seems fine:

```
[20:19:14] [Client thread/INFO] [XCompCraft]: Searching for SimpleDim configuration files...
[20:19:14] [Client thread/INFO] [XCompCraft]: Found miningworld.cfg
[20:19:14] [Client thread/INFO] [XCompCraft]: Found configuration for dimMiningworlddim with ID 16
[20:19:14] [Client thread/INFO] [XCompCraft]: Found item configuration for porterMiningworlddim for dimension dimMiningworlddim
[20:19:14] [Client thread/INFO] [XCompCraft]: Finished parsing 1 dimensions and 1 items from miningworld.cfg
[20:19:14] [Client thread/INFO] [XCompCraft]: Finished searching for SimpleDim configs. Found a total of 1 dimension entries and 1 transport items.
```

I make a new world and try to use the teleport item. The game crashes:

```
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 14/09/15 20:21
Description: Ticking player

java.lang.NullPointerException: Ticking player
    at nil.xcompcraft.item.TeleporterItem.func_77654_b(TeleporterItem.java:50)
    at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:151)
    at net.minecraft.entity.player.EntityPlayer.func_71036_o(EntityPlayer.java:419)
    at net.minecraft.entity.player.EntityPlayerMP.func_71036_o(EntityPlayerMP.java:866)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:242)
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at nil.xcompcraft.item.TeleporterItem.func_77654_b(TeleporterItem.java:50)
    at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:151)
    at net.minecraft.entity.player.EntityPlayer.func_71036_o(EntityPlayer.java:419)
    at net.minecraft.entity.player.EntityPlayerMP.func_71036_o(EntityPlayerMP.java:866)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:242)

-- Player being ticked --
Details:
    Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
    Entity ID: 168
    Entity Name: leftyyy
    Entity's Exact location: 55.87, 66.00, 230.24
    Entity's Block location: World: (55,66,230), Chunk: (at 7,4,6 in 3,14; contains blocks 48,0,224 to 63,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@db57acd
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

Already tested void and superflat and they work fine.

**Comment by spocane** [comment]
"singleBiome" is working fine for me using: 

-- Meadow { id: -13; type: singleBiome; biome: meadow } 

(Meadow Biome is from BOP)

**Comment by lefty82** [comment]
@spocane changing my dimension IDs to negative seems to have solved the always crash, I do sometimes get an error though when teleporting much like the log I posted above. It seems that they are two different bugs. One with  non negative ID's and one with sometimes buggy teleport.

**Comment by MysteriousAges** [comment]
I'm having some difficulty reproducing this in dev reliably. Could you also post your mod config file contents please?

**Comment by lefty82** [comment]
Hello.

Unfortunately I cannot replicate the bug either! It used to be that non negative dimension ID's crashed (sometimes) the game and also desert and plains biomes crashed (the moment of teleport). Now no crashes are happening at all. The crashes were happening with just NEI as the only other mod present.

The only crash report I can provide is the one in the previous message that used to happen all the time.

This is the code that I am using right now for gameplay that used to crash but no longer does:

```
### Mining Dimension
dimMiningworld { id: -30; type: singleBiome; biome: Desert; loadSpawn: false; }
item porterMiningworld { forDim: dimMiningworld; type: accesscard; colours: [0xffffcc]; displayName: "Mining Dimension Pass"; }


### Building Dimension
dimBasebuilding { id: -31; type: singleBiome; biome: Plains; loadSpawn: false;}
item porterBasebuilding { forDim: dimBasebuilding; type: accesscard; colours: [0xffffcc]; displayName: "Building Dimension Pass"; }
```

**Comment by MysteriousAges** [comment]
The only time I've managed the crash so far was the very first time I tried TPing into the dimension, and even then, it only happened once out of 5 times testing it.

Can you try a positive dimension ID and try to replicate the crash please?

**Comment by lefty82** [comment]
Can't seem to replicate as well, it seems that I was just unlucky on that day and kept getting errors.
